# fly.toml app configuration file generated for agendaapp on 2025-03-27T22:03:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file generated for agendaapp on 2025-03-27T22:03:09Z

app = 'agendaapp'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  count = 3
  memory_mb = 1024

[services]
  [[services.http]]
  internal_port = 8080
  force_https = true
  
  [services.http.healthchecks]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    max_consecutive_failures = 5
    path = "/health"
    method = "GET"

[deploy]
  strategy = "rolling"
  max_unavailable = 0
  auto_rollback = true

[auto_scaling]
  min_machines = 2
  max_machines = 3
  cpu_threshold = 70
  memory_threshold = 80
